package edu.tucn.scd.serverapp.position;

import com.fasterxml.jackson.annotation.JsonProperty;
import edu.tucn.scd.serverapp.terminal.Terminal;
import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

import java.util.Date;

/**
 * @author Radu Miron
 * @version 1
 */

@Entity // Această anotare indică faptul că clasa este o entitate JPA, reprezentând o tabelă în baza de date.
@Data   // Anotarea Lombok generează automat metodele standard: equals(), hashCode() și toString().
public class Position {

    @Id // PK
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increment
    private Integer id;

    private String latitude;
    private String longitude;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    // Definește o relație Many-To-One cu entitatea Terminal. 'FetchType.LAZY' încarcă datele la cerere.
    @JoinColumn(name = "terminal_id", nullable = false)
    @OnDelete(action = OnDeleteAction.CASCADE)
    // Specifică acțiunea de CASCADE pentru ștergerea: dacă un terminal este șters, toate pozițiile sale vor fi, de asemenea, șterse.
    private Terminal terminal;

    @Column(updatable = false, nullable = false) // autogenerated value
    @CreationTimestamp // sets value to current time
    private Date creationDate;
}
